#pragma warning disable CS1591
// Code Generated by DLaB.ModelBuilderExtensions
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECC.Core.DataContext
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CreateTrainEffortModelConfig")]
	public partial class Msdyn_CreateTrainEffortModelConfigRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string EntityLogicalName = "EntityLogicalName";
			public const string RecordId = "RecordId";
			public const string DataBinding = "DataBinding";
			public const string CustomConfig = "CustomConfig";
		}
		
		public const string ActionLogicalName = "msdyn_CreateTrainEffortModelConfig";
		
		public string EntityLogicalName
		{
			get
			{
				if (this.Parameters.Contains("EntityLogicalName"))
				{
					return ((string)(this.Parameters["EntityLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityLogicalName"] = value;
			}
		}
		
		public string RecordId
		{
			get
			{
				if (this.Parameters.Contains("RecordId"))
				{
					return ((string)(this.Parameters["RecordId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RecordId"] = value;
			}
		}
		
		public string DataBinding
		{
			get
			{
				if (this.Parameters.Contains("DataBinding"))
				{
					return ((string)(this.Parameters["DataBinding"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["DataBinding"] = value;
			}
		}
		
		public string CustomConfig
		{
			get
			{
				if (this.Parameters.Contains("CustomConfig"))
				{
					return ((string)(this.Parameters["CustomConfig"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CustomConfig"] = value;
			}
		}
		
		public Msdyn_CreateTrainEffortModelConfigRequest()
		{
			this.RequestName = "msdyn_CreateTrainEffortModelConfig";
			this.EntityLogicalName = default(string);
			this.RecordId = default(string);
			this.DataBinding = default(string);
			this.CustomConfig = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_CreateTrainEffortModelConfig")]
	public partial class Msdyn_CreateTrainEffortModelConfigResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string TrainConfig = "TrainConfig";
		}
		
		public const string ActionLogicalName = "msdyn_CreateTrainEffortModelConfig";
		
		public Msdyn_CreateTrainEffortModelConfigResponse()
		{
		}
		
		public string TrainConfig
		{
			get
			{
				if (this.Results.Contains("TrainConfig"))
				{
					return ((string)(this.Results["TrainConfig"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["TrainConfig"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
